kafka:
  brokers:
    - localhost:9092
  topics: 
    - convert
    - diarize
    - transcribe
  group_id: ${KAFKA_GROUP_ID}

tokens:
  hf_token: ${HF_TOKEN}

ollama:
  url: ${OLLAMA_URL}
  model: ${OLLAMA_MODEL}
  num_context: ${OLLAMA_NUM_CONTEXT}