kafka:
  brokers:
    - localhost:9092
  topic: tasks
  group_id: ${KAFKA_GROUP_ID}

tokens:
  hf_token: ${HF_TOKEN}

ollama:
  url: ${OLLAMA_URL}
  model: ${OLLAMA_MODEL}
  num_context: ${OLLAMA_NUM_CONTEXT}